openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/patient/register:
    post:
      tags:
      - authentication-controller
      operationId: registerPatient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PatientDto'
  /api/v1/patient/login:
    post:
      tags:
      - authentication-controller
      operationId: loginPatient
      parameters:
      - name: email
        in: query
        required: true
        schema:
          type: string
      - name: password
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PatientDto'
components:
  schemas:
    PatientDto:
      type: object
      properties:
        patientId:
          type: integer
          format: int32
        email:
          type: string
        title:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dob:
          type: string
        contactNumber:
          type: string
        password:
          type: string
        gender:
          type: string
        address:
          type: string
